apiVersion: v1
kind: Service
metadata:
  name: loki-grafana
  namespace: logging   # Replace with the appropriate namespace
spec:
  type: NodePort
  selector:
    app: loki-grafana       # Replace with the actual selector labels if different
  ports:
    - port: 80              # Service port
      targetPort: 80        # Target port in the Grafana container
      nodePort: 30080       # Optional: specify the NodePort (default range 30000-32767)

